spring:
  cloud:
    gateway:
      default-filters:
          - AddResponseHeader=X-Response-HELLO, WORLD
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #在eureka中，服务是以大写的形式注册的，可以转化成小写
      routes:
        - id: order-service #服务唯一ID标识
          uri: lb://order-service # 注册中心的服务id
          predicates:
            - Path=/order/** #请求转发
          filters:
            - StripPrefix=1 #切割请求，去除/order/
        #TODO: 添加Inventory Service的反向代理

        - id: header_route
          uri: http://baidu.com
          predicates:
          - Header=X-Request-Site, baidu
  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://zipkin.team-a.cloud.school.thoughtworks.cn

logging:
  level:
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
